version: '3.7' 

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
          - ./app:/app
    environment:
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
# Names our volume
volumes:
  db: